version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: delta_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "PGPASSWORD=$DATABASE_PASSWORD DATABASE_USER=$DATABASE_USER /wait-for-db.sh db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=delta_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=xxxx
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
