--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO postgres;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO postgres;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delta_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delta_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    status boolean NOT NULL,
    signature character varying(100),
    uh_id character varying(10)
);


ALTER TABLE public.delta_customuser OWNER TO postgres;

--
-- Name: delta_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delta_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.delta_customuser_groups OWNER TO postgres;

--
-- Name: delta_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delta_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delta_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delta_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delta_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delta_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delta_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delta_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.delta_customuser_user_permissions OWNER TO postgres;

--
-- Name: delta_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delta_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delta_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delta_generalpetition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delta_generalpetition (
    id bigint NOT NULL,
    student_last_name character varying(100) NOT NULL,
    student_first_name character varying(100) NOT NULL,
    student_middle_name character varying(100),
    student_uh_id character varying(20) NOT NULL,
    student_phone_number character varying(20),
    student_program_plan character varying(100) NOT NULL,
    student_academic_career character varying(100) NOT NULL,
    student_mailing_address text NOT NULL,
    student_city character varying(100) NOT NULL,
    student_state character varying(50) NOT NULL,
    student_zip_code character varying(10) NOT NULL,
    student_email character varying(254) NOT NULL,
    program_status_action character varying(100),
    admission_status_from character varying(100),
    admission_status_to character varying(100),
    new_career character varying(100),
    post_bac_study_objective character varying(100),
    second_bachelor_plan boolean NOT NULL,
    graduate_study_objective boolean NOT NULL,
    teacher_certification boolean NOT NULL,
    personal_enrichment_objective boolean NOT NULL,
    program_change_from character varying(100),
    program_change_to character varying(100),
    plan_change_from character varying(100),
    plan_change_to character varying(100),
    degree_objective_change_from character varying(100),
    degree_objective_change_to character varying(100),
    requirement_term_year character varying(4),
    requirement_term_catalog character varying(100),
    requirement_term_career character varying(100),
    requirement_term_program_plan character varying(100),
    additional_plan_degree_type character varying(50),
    is_new_plan_primary_or_secondary character varying(50),
    other_current_plans_or_minors text,
    second_degree_type character varying(100),
    minor_change_from character varying(100),
    minor_change_to character varying(100),
    additional_minor character varying(100),
    degree_requirement_exception_details text,
    special_problems_course_list text,
    course_overload_gpa character varying(10),
    course_overload_credit_hours character varying(10),
    course_overload_course_list text,
    graduate_leave_of_absence_request_details text,
    graduate_reinstatement_request_details text,
    other_request_details text,
    explanation_of_request text,
    student_signature character varying(100),
    signature_date date,
    date_submitted date NOT NULL
);


ALTER TABLE public.delta_generalpetition OWNER TO postgres;

--
-- Name: delta_generalpetition_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delta_generalpetition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delta_generalpetition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delta_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delta_notification (
    id bigint NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    recipient_id bigint NOT NULL
);


ALTER TABLE public.delta_notification OWNER TO postgres;

--
-- Name: delta_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delta_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delta_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delta_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delta_request (
    id bigint NOT NULL,
    request_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    date_created date NOT NULL,
    current_major character varying(100),
    new_major character varying(100),
    old_address character varying(255),
    new_address character varying(255),
    pdf_file character varying(100),
    user_id bigint NOT NULL,
    explanation text,
    first_name character varying(50),
    last_name character varying(50),
    email character varying(254),
    supporting_documents character varying(100),
    uh_id character varying(20)
);


ALTER TABLE public.delta_request OWNER TO postgres;

--
-- Name: delta_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delta_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delta_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO postgres;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO postgres;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO postgres;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO postgres;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO postgres;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add email address	7	add_emailaddress
26	Can change email address	7	change_emailaddress
27	Can delete email address	7	delete_emailaddress
28	Can view email address	7	view_emailaddress
29	Can add email confirmation	8	add_emailconfirmation
30	Can change email confirmation	8	change_emailconfirmation
31	Can delete email confirmation	8	delete_emailconfirmation
32	Can view email confirmation	8	view_emailconfirmation
33	Can add social application	9	add_socialapp
34	Can change social application	9	change_socialapp
35	Can delete social application	9	delete_socialapp
36	Can view social application	9	view_socialapp
37	Can add social account	10	add_socialaccount
38	Can change social account	10	change_socialaccount
39	Can delete social account	10	delete_socialaccount
40	Can view social account	10	view_socialaccount
41	Can add social application token	11	add_socialtoken
42	Can change social application token	11	change_socialtoken
43	Can delete social application token	11	delete_socialtoken
44	Can view social application token	11	view_socialtoken
45	Can add user	12	add_customuser
46	Can change user	12	change_customuser
47	Can delete user	12	delete_customuser
48	Can view user	12	view_customuser
49	Can add request	13	add_request
50	Can change request	13	change_request
51	Can delete request	13	delete_request
52	Can view request	13	view_request
53	Can add notification	14	add_notification
54	Can change notification	14	change_notification
55	Can delete notification	14	delete_notification
56	Can view notification	14	view_notification
57	Can add general petition	15	add_generalpetition
58	Can change general petition	15	change_generalpetition
59	Can delete general petition	15	delete_generalpetition
60	Can view general petition	15	view_generalpetition
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$870000$kG32BWz6UDdCWy3gSGL1NF$oqi6gOru15FXvU5s7+xbaABJUYcc2e4R8wm372SoF9I=	2025-02-19 14:35:52.74805-06	f	nam_test			namtest@gmail.com	f	t	2025-02-19 14:35:38.980452-06
2	pbkdf2_sha256$870000$47iP3jJACHdLvX072lKXNs$wAJ67QHAQR6pvU4unn3vCdcXwFcv110fcLs7VWWWBbo=	2025-02-19 21:10:59.13246-06	t	nam_admin			namnc23@gmail.com	t	t	2025-02-19 14:39:15.393625-06
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: delta_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delta_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, status, signature, uh_id) FROM stdin;
1	pbkdf2_sha256$870000$60WAH1IkvMaOwXlYgtUczb$Ix+iwhlppSqnyBhn2fNCAzWjZ9W9OTO4h5WbzwLZxNE=	2025-03-30 21:23:08.879481-05	t	can_admin				t	t	2025-03-30 21:21:49.098268-05	basicuser	t	\N	\N
\.


--
-- Data for Name: delta_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delta_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: delta_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delta_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: delta_generalpetition; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delta_generalpetition (id, student_last_name, student_first_name, student_middle_name, student_uh_id, student_phone_number, student_program_plan, student_academic_career, student_mailing_address, student_city, student_state, student_zip_code, student_email, program_status_action, admission_status_from, admission_status_to, new_career, post_bac_study_objective, second_bachelor_plan, graduate_study_objective, teacher_certification, personal_enrichment_objective, program_change_from, program_change_to, plan_change_from, plan_change_to, degree_objective_change_from, degree_objective_change_to, requirement_term_year, requirement_term_catalog, requirement_term_career, requirement_term_program_plan, additional_plan_degree_type, is_new_plan_primary_or_secondary, other_current_plans_or_minors, second_degree_type, minor_change_from, minor_change_to, additional_minor, degree_requirement_exception_details, special_problems_course_list, course_overload_gpa, course_overload_credit_hours, course_overload_course_list, graduate_leave_of_absence_request_details, graduate_reinstatement_request_details, other_request_details, explanation_of_request, student_signature, signature_date, date_submitted) FROM stdin;
\.


--
-- Data for Name: delta_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delta_notification (id, message, created_at, is_read, recipient_id) FROM stdin;
\.


--
-- Data for Name: delta_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delta_request (id, request_type, status, date_created, current_major, new_major, old_address, new_address, pdf_file, user_id, explanation, first_name, last_name, email, supporting_documents, uh_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	account	emailaddress
8	account	emailconfirmation
9	socialaccount	socialapp
10	socialaccount	socialaccount
11	socialaccount	socialtoken
12	delta	customuser
13	delta	request
14	delta	notification
15	delta	generalpetition
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-03-16 20:29:17.714095-05
2	contenttypes	0002_remove_content_type_name	2025-03-16 20:29:17.72187-05
3	auth	0001_initial	2025-03-16 20:29:17.768662-05
4	auth	0002_alter_permission_name_max_length	2025-03-16 20:29:17.773745-05
5	auth	0003_alter_user_email_max_length	2025-03-16 20:29:17.776296-05
6	auth	0004_alter_user_username_opts	2025-03-16 20:29:17.780841-05
7	auth	0005_alter_user_last_login_null	2025-03-16 20:29:17.785486-05
8	auth	0006_require_contenttypes_0002	2025-03-16 20:29:17.787018-05
9	auth	0007_alter_validators_add_error_messages	2025-03-16 20:29:17.791062-05
10	auth	0008_alter_user_username_max_length	2025-03-16 20:29:17.794347-05
11	auth	0009_alter_user_last_name_max_length	2025-03-16 20:29:17.798413-05
12	auth	0010_alter_group_name_max_length	2025-03-16 20:29:17.802621-05
13	auth	0011_update_proxy_permissions	2025-03-16 20:29:17.806542-05
14	auth	0012_alter_user_first_name_max_length	2025-03-16 20:29:17.81022-05
15	delta	0001_initial	2025-03-16 20:29:17.861487-05
16	account	0001_initial	2025-03-16 20:29:17.895783-05
17	account	0002_email_max_length	2025-03-16 20:29:17.903134-05
18	account	0003_alter_emailaddress_create_unique_verified_email	2025-03-16 20:29:17.916249-05
19	account	0004_alter_emailaddress_drop_unique_email	2025-03-16 20:29:17.931305-05
20	account	0005_emailaddress_idx_upper_email	2025-03-16 20:29:17.941176-05
21	account	0006_emailaddress_lower	2025-03-16 20:29:17.951533-05
22	account	0007_emailaddress_idx_email	2025-03-16 20:29:17.96952-05
23	account	0008_emailaddress_unique_primary_email_fixup	2025-03-16 20:29:17.980277-05
24	account	0009_emailaddress_unique_primary_email	2025-03-16 20:29:17.987424-05
25	admin	0001_initial	2025-03-16 20:29:18.006782-05
26	admin	0002_logentry_remove_auto_add	2025-03-16 20:29:18.013491-05
27	admin	0003_logentry_add_action_flag_choices	2025-03-16 20:29:18.020875-05
28	sessions	0001_initial	2025-03-16 20:29:18.031584-05
29	sites	0001_initial	2025-03-16 20:29:18.036846-05
30	sites	0002_alter_domain_unique	2025-03-16 20:29:18.043544-05
31	socialaccount	0001_initial	2025-03-16 20:29:18.112539-05
32	socialaccount	0002_token_max_lengths	2025-03-16 20:29:18.129575-05
33	socialaccount	0003_extra_data_default_dict	2025-03-16 20:29:18.137233-05
34	socialaccount	0004_app_provider_id_settings	2025-03-16 20:29:18.153613-05
35	socialaccount	0005_socialtoken_nullable_app	2025-03-16 20:29:18.168816-05
36	socialaccount	0006_alter_socialaccount_extra_data	2025-03-16 20:29:18.185738-05
37	delta	0002_request_explanation_request_first_name_and_more	2025-03-16 22:44:16.835038-05
38	delta	0003_alter_request_first_name_alter_request_last_name	2025-03-16 22:46:56.334459-05
39	delta	0002_remove_customuser_signature_alter_customuser_groups_and_more	2025-04-07 12:39:57.792044-05
40	delta	0003_customuser_signature	2025-04-07 12:39:57.802742-05
41	delta	0004_merge_20250317_1152	2025-04-07 12:39:57.804279-05
42	delta	0005_remove_request_date_updated_and_more	2025-04-07 12:39:57.84177-05
43	delta	0006_request_explanation_request_first_name_and_more	2025-04-07 12:39:57.858528-05
44	delta	0007_customuser_uh_id	2025-04-07 12:39:57.865594-05
45	delta	0008_alter_customuser_is_active	2025-04-07 12:39:57.872156-05
46	delta	0009_notification	2025-04-07 12:39:57.907202-05
47	delta	0010_request_email_request_supporting_documents_and_more	2025-04-07 12:39:57.92527-05
48	delta	0010_generalpetition	2025-04-12 16:57:55.371592-05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
q85ef8rnde05g0rt828novcq84mmpy3i	.eJxVkMFuwyAMht_F5wiFQALkuHufYJqQAW9hW6AKRO1U9d0Xtl56s_z9_mz5Buh93lO1uNeFUo0ea8zJrlSXHArMrzf4r2GGM5ZyyVuADrDCzJUUQiulNdNqFH0_dLAX2hKudKQ9JothjQnubx38LbAN29hcHJ56Dv0XpQbCJ6aPzHxOdYuOtQh70MJOOdD3yyP7JFiwLMe04ZoHN00GhzCNJFGKd8m1QdISRSBvRuk8CWV4z4_L3SiMoIEGrhQFwiYtVEr7AV3PcfuBub__Au1UYZg:1tz4ns:wgjloMcKM8FVE3PDljVhZ5r6U8bWabiX26LnM592j6w	2025-04-13 21:23:08.879481-05
095iauo5tcyiptkllkf95a2mky9oma3d	.eJyd0c1yokAABOB34azZQUCZ3BBEjYjhJ5Bha4ti-JFRGGBgFEnl3dcHyCnn7kN_1V9C36QkqZI0bTgd4n5IhrwXXr8E3E31_kpVWhU6rB0svP79ElrWpHn_zIWqORMqzIQsGRLhlfKqmgntNc3jtMny-JYzUpCcPYsGtO8bcLhM19gvacnt2C0siLLO54qK4KiUMbs8TFocXdN9y7D6uKndnD7CGzKdZhTH-i0COir9tI2Yy6Ogw_rHusKM4PcbnOxyxBfvTsZ13Hn4LclVcWHpnJdpcs3JuTo8N9J8HJ5L_gjfM3ElAwCgAuQXSVJXykr6NxP81FMA86yqPXMiRe5vqWapne1QOjGLufUSHIvB1UIi39AxRGC914opTkroD0Vf2L1VDCxCO34nk4Ks_YGmoXPfhHqNl3O_7LIi07i52OHwYQANvNfx4iyq0XaPgnu3K6HYK5p0og9CLEMehybe7owfqXApvQAoypK4fFJHJ-lPPR75ZasyffPxW6r9PITK5yQMaLDRkdhU0VaT2EQsD8_TxIu0aUGNT5FEshFvWWe8-x2Wl50u9gG024qfTNDwPPhIwmUb9MMnWm1WHXS3sJlrh3Qy1TWoTY9kyLGPqnlvzba384I7Oiqi2Ml-oIoAyOBlpSoKAMq_7-__8IbxRw:1tku64:afEhSpr01xJdWAHfGHYXVQS9O7x-eWoTdVrEf0H2d40	2025-03-05 18:07:20.7865-06
dbzonw3sy2nzwc90rx15emzf1wn7q2yn	eyJzb2NpYWxhY2NvdW50X3N0YXRlcyI6e319:1tkx7w:D73nvaXY6mUJK52Q1cCLrZzNl9KtSMpJ6pRlouWas7U	2025-03-05 21:21:28.479816-06
r8nou9mn0c9vlee6jxa7jnzr3uh6m383	.eJyd1Leyo1gUBdB_UdxouHg6w0h4D8JMdVGA8AgrBKir_33UE7_oJTc5N9ir9qnz-7QMWZ10SZYNa_-Ml2fyzJfTz98nano1RkZYWcWNDLxcTj___X0a5yHLl8_81A1l3Z9-nO7JMzn97Neu-3Ea2yyPs-Gex698ros6nz8fmfrOVEZZmXesBQ57H5FuHnaYJZbZnW-Rmd3CpALmSBgsr7iw53VXSGe53XuZj7JlFGcMvKHGGE8HLnJp8ezSvqDYYR7QPB0Fao6bCK2aPCwY81Sw2hW1p325g9BKc0LwufyTsc_35yfJP6c_PwCJwTBMoSR6JkiYIKhfP06BZUnS8xIMuudsNmp-V0rUZNozGsofyQuzYLpkr9dhoQST6ZiHzjr9TYhjxrz7HAI7yew3B71Tqk3N6gV4kDxBLMXRYzGXuUzgvbgX3e2-GFK4Jdlxx_wktAn55bEoXgy8LkHcZj64dHvF2UEcywHAl1Iahs8IguEkRXyoIW7zRmMcowgIDBvf3y61nMq3jQjDjKKKEQGpGq-KgjX15eJmkqEZK6K2zwYU-TB7Od3KK0tE6kRQsP5asKClEnth6ZR8CT2kqkomS-IbffSrpXlXf5nkVSncTZpET9MgIRsD4Ri2grGuaV8rY1LGX1FpACPnjxPAMPKhEmXFgAD3HdlBBaFuv0ut3u0zKKH2OlbO1r3fdmQh-Xqh9cQ5yo2L0QDJ96BUoizswYzuSQH4N6LK-LJSinJNYOcTbzMnPaUjn91MYM1P1oi6oGmaycQ9vptNj2KrtbpyCEcWDSqE1wky7CMhQZ2-v6T-3V-EAIAk0Q812u8dWndjl9iNKKfud6mPuI7SdxnkJPVi-OwShQebtX3AAkgg12GwGSkS-rwSeW3q_Vnvjt22nefcI33fX4bZBMrdVgUPfjVJvdkHcK3bDD943gwUTT94FapvCuq4hdoOE0bF_EyF4kPUAUYUuHsjvqB-yiSRM4ligP6_VdygFmHoIrgiREfrrt-lri9op_jCU_totA3xOtND6veQpnroPu26JN31Xq8OsqE9GAk7NZYrC79t5KRyHqzT1YKTbmdkQp_AZcRt6OOqaVUBVmgm-jvdCGV8qRM3h2cBk3J1RzTZKu_CvNn3VwDQh_wlFcD4GQEoTYOPlNJLDLCkxLpSzanh8V2pUNHja783rdpNvroSb5K9SrS0xdlzGKPYr4TySLOSUp6l5AwkHQvW43YJPNIhXH8UpmCW9FngrIwYuvZmqS1upLjkQggn2HR-HGw8YcEiag-nO1w1MbEKB93bn9WCk5eISr6UoiRx_jwYSv89wGLH03rbIWHaPPtOor9LpbW3CfVhtjK005MW23B7NmIY5rL2VgTpEfKqhsnuQL_oCj3A5u_BWPc-TVwFP5P9JG3RwkJK_Ioaooy6bXabHsIllQyJF0WGFtsxbl5MSyOfSzRm-QzcPpw9PYYfwkTy_telYgg4w4DCEfTv_m6XG57uK7E3bkjosvJdqivmFn3JII8pD9x--jqUUBniLd1S4fCxZ6kFN66Xa0EwkLfEtZfVGIo1DeeZLSqhwT-t4nzElbzK87ebqNZvyHk09Fs7Hl7vLI1XV7IAg5hm1fixWGJz3yDonZetZ4cpqoRfUnGSPGOfcgH-68-f_wART7AH:1tkuOG:9GvdD6OqlMkbdgIUDdsAPS-ne0L-8PNpBDv05Tu7evk	2025-03-05 18:26:08.752188-06
4n5sj5eq4jeiyu1ho52e1xw4ww642k2a	.eJyd0UlzolAUBeD_wlrTgI8pOzGiyCwqYleKwsdjfMyTkMp_b3qfVdb3Ls53zhfRljDxsQ9h2Red13Z-h1ri_YuIAZBbyKqgPlIyl-fE-98vompKiNrlTuAySgpiRQR-5xPvRY_xiqgyiDxYBsgbUJOECWqWx5wywVNogkit_WG9YSt2YifJ0-IbE1pzKGGtLwJOcZHuibs-M1ufj7MXHvOZv4rnns6Qp-VG6hStheu9na0rpZXujG0WJ7XT-P2-agbLPmuNc1dSnr_GW9U3Ykl3Hm0Qt-7_jAV6dUuSP8T3iuIASVIUS4I3kqY3JEt_rogX636o0uVhT0cuNLL5t1R4ZWL7HE1-4yA9j9JW25gV8nrDgNtYxsHugE9r-CFnjpkHkyJMpp_SNxr6bqWLmQH4Zh-FPk3Sj8FUja2IjFAvzkpqOdk2KOO6NmNuLHbla76H3lp7OGmti9NQgJfpyqJ3-olKM2ChshuaptmFer_vCqnmaAsts-i4-i3VabJRYS40dXKs_WzqFi-FBjpiQcjxHB2UGlWX3g3lZP2YFQ0-uTE-mnaTrOdWQ4LU8efazbEYZu7Adidj3DwuKNJb5nVUIbmsDZ-zbEzrTpBHt5HvlgB2EA8K77KT0jn5j1QO8NQbIBmaYriFWqS3HPqSMgQggNcn-C213ml2ZjwLScx78nrci0KAxcrE-WaUO5IF1MiS7vyQkZtQxf4Ay_mpRiLgEBmad9fZAyk66Om0icQdxcGl82S8PX25U9RRSmWrT8-yZfY253jr7cFIoY-U-HqOEtx89GH52P5E5UmSX1ZlSE6gP7-__wEf8Txi:1tkwAa:19I48LnFVTw8BqNLThkXbV9lezr0Scr-TtAS_JfoUUw	2025-03-05 20:20:08.066078-06
3kcfg5rb18cryvw9uws9phksy2b84oyz	.eJydz8tyqjAAgOF3yVo63JKAOwJHBEWllWpPp8NgiJZ7uIOO797uzv6s_3_zPUBb0STKI0qrvuzCtos61oLlA2AeG7E9p2YiXkYlmMHy8wF4U1HW_naQV7ekBAsQR10ElmWf5wvAM8pCWsUsHFiTXBPW_I5lHvR2u4oQJ5qieGV7yqXcTdmBfOh0ikrbluv7XTrKVJkgfw1woxAT9mfZvFHLcYbr5QyDG5cIFHBWvdXodfIP5l5OcSiMH-oaCwIt3cN6U6QaN7ZTLTj2XWndC8xDQjMLPBcSVkVR0pGOXiSkK7KGvxaA6sWWrM3Tivwh21bd_K9vdwoGSy_irLG0ox_OlXfGQ4grbqzQKMEoOwaQZWgKZn3wmSEeDbpPXb_l0TzI79xR-vFOZexsUsPKm6SWRw_tvOzQ7Q0trQvytyDX9-TbPwkey9a2snVHXse7G1SnS12pxT8fxuILUhGUoPr1fP4AVzubBw:1tkwd0:8Uk6Ws60RyHHQIGppbwEO9Vz8enfcTZ3Hqm0aOtrUd4	2025-03-05 20:49:30.647515-06
08f48kiuyjzrvtrfbbo14doivuyhkvob	eyJzb2NpYWxhY2NvdW50X3N0YXRlcyI6e319:1tkx19:HFvX96SV-bOGj55PpYxL-VMPAOUICfoKF03GhOLEEaw	2025-03-05 21:14:27.776116-06
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_site (id, domain, name) FROM stdin;
1	example.com	example.com
\.


--
-- Data for Name: socialaccount_socialaccount; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.socialaccount_socialaccount (id, provider, uid, last_login, date_joined, extra_data, user_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.socialaccount_socialapp (id, provider, name, client_id, secret, key, provider_id, settings) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp_sites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.socialaccount_socialapp_sites (id, socialapp_id, site_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.socialaccount_socialtoken (id, token, token_secret, expires_at, account_id, app_id) FROM stdin;
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 2, true);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: delta_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delta_customuser_groups_id_seq', 1, false);


--
-- Name: delta_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delta_customuser_id_seq', 1, true);


--
-- Name: delta_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delta_customuser_user_permissions_id_seq', 1, false);


--
-- Name: delta_generalpetition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delta_generalpetition_id_seq', 1, false);


--
-- Name: delta_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delta_notification_id_seq', 1, false);


--
-- Name: delta_request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delta_request_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 33, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.socialaccount_socialaccount_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_sites_id_seq', 1, false);


--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.socialaccount_socialtoken_id_seq', 1, false);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: delta_customuser_groups delta_customuser_groups_customuser_id_group_id_6d22681f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_groups
    ADD CONSTRAINT delta_customuser_groups_customuser_id_group_id_6d22681f_uniq UNIQUE (customuser_id, group_id);


--
-- Name: delta_customuser_groups delta_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_groups
    ADD CONSTRAINT delta_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: delta_customuser delta_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser
    ADD CONSTRAINT delta_customuser_pkey PRIMARY KEY (id);


--
-- Name: delta_customuser_user_permissions delta_customuser_user_pe_customuser_id_permission_99900c17_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_user_permissions
    ADD CONSTRAINT delta_customuser_user_pe_customuser_id_permission_99900c17_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: delta_customuser_user_permissions delta_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_user_permissions
    ADD CONSTRAINT delta_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: delta_customuser delta_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser
    ADD CONSTRAINT delta_customuser_username_key UNIQUE (username);


--
-- Name: delta_generalpetition delta_generalpetition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_generalpetition
    ADD CONSTRAINT delta_generalpetition_pkey PRIMARY KEY (id);


--
-- Name: delta_notification delta_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_notification
    ADD CONSTRAINT delta_notification_pkey PRIMARY KEY (id);


--
-- Name: delta_request delta_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_request
    ADD CONSTRAINT delta_request_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: delta_customuser_groups_customuser_id_55ba8650; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delta_customuser_groups_customuser_id_55ba8650 ON public.delta_customuser_groups USING btree (customuser_id);


--
-- Name: delta_customuser_groups_group_id_4db2a26e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delta_customuser_groups_group_id_4db2a26e ON public.delta_customuser_groups USING btree (group_id);


--
-- Name: delta_customuser_user_permissions_customuser_id_362d2601; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delta_customuser_user_permissions_customuser_id_362d2601 ON public.delta_customuser_user_permissions USING btree (customuser_id);


--
-- Name: delta_customuser_user_permissions_permission_id_ca8b8d67; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delta_customuser_user_permissions_permission_id_ca8b8d67 ON public.delta_customuser_user_permissions USING btree (permission_id);


--
-- Name: delta_customuser_username_d984bc91_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delta_customuser_username_d984bc91_like ON public.delta_customuser USING btree (username varchar_pattern_ops);


--
-- Name: delta_notification_recipient_id_c0887df6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delta_notification_recipient_id_c0887df6 ON public.delta_notification USING btree (recipient_id);


--
-- Name: delta_request_user_id_2eff7d6d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX delta_request_user_id_2eff7d6d ON public.delta_request USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_delta_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_delta_customuser_id FOREIGN KEY (user_id) REFERENCES public.delta_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: delta_customuser_groups delta_customuser_gro_customuser_id_55ba8650_fk_delta_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_groups
    ADD CONSTRAINT delta_customuser_gro_customuser_id_55ba8650_fk_delta_cus FOREIGN KEY (customuser_id) REFERENCES public.delta_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: delta_customuser_groups delta_customuser_groups_group_id_4db2a26e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_groups
    ADD CONSTRAINT delta_customuser_groups_group_id_4db2a26e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: delta_customuser_user_permissions delta_customuser_use_customuser_id_362d2601_fk_delta_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_user_permissions
    ADD CONSTRAINT delta_customuser_use_customuser_id_362d2601_fk_delta_cus FOREIGN KEY (customuser_id) REFERENCES public.delta_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: delta_customuser_user_permissions delta_customuser_use_permission_id_ca8b8d67_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_customuser_user_permissions
    ADD CONSTRAINT delta_customuser_use_permission_id_ca8b8d67_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: delta_notification delta_notification_recipient_id_c0887df6_fk_delta_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_notification
    ADD CONSTRAINT delta_notification_recipient_id_c0887df6_fk_delta_customuser_id FOREIGN KEY (recipient_id) REFERENCES public.delta_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: delta_request delta_request_user_id_2eff7d6d_fk_delta_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delta_request
    ADD CONSTRAINT delta_request_user_id_2eff7d6d_fk_delta_customuser_id FOREIGN KEY (user_id) REFERENCES public.delta_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_delta_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_delta_customuser_id FOREIGN KEY (user_id) REFERENCES public.delta_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_social_user_id_8146e70c_fk_delta_cus; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_social_user_id_8146e70c_fk_delta_cus FOREIGN KEY (user_id) REFERENCES public.delta_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

