# Generated by Django 5.1.6 on 2025-03-30 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='uh_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('returned', 'Returned'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delta.customuser')),
            ],
        ),
    ]
