# Generated by Django 5.1.6 on 2025-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0006_request_explanation_request_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='uh_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
