# Generated by Django 5.1.7 on 2025-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0007_customuser_uh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
