# Generated by Django 5.1.6 on 2025-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0007_remove_customuser_is_active_status_customuser_uh_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active_status',
            field=models.BooleanField(default=True, verbose_name='active status'),
        ),
    ]
