# Generated by Django 5.1.6 on 2025-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_uh_id', models.CharField(max_length=20)),
                ('student_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('student_program_plan', models.CharField(max_length=100)),
                ('student_academic_career', models.CharField(max_length=100)),
                ('student_mailing_address', models.TextField()),
                ('student_city', models.CharField(max_length=100)),
                ('student_state', models.CharField(max_length=50)),
                ('student_zip_code', models.CharField(max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
                ('program_status_action', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_status_from', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_status_to', models.CharField(blank=True, max_length=100, null=True)),
                ('new_career', models.CharField(blank=True, max_length=100, null=True)),
                ('post_bac_study_objective', models.CharField(blank=True, max_length=100, null=True)),
                ('second_bachelor_plan', models.BooleanField(default=False)),
                ('graduate_study_objective', models.BooleanField(default=False)),
                ('teacher_certification', models.BooleanField(default=False)),
                ('personal_enrichment_objective', models.BooleanField(default=False)),
                ('program_change_from', models.CharField(blank=True, max_length=100, null=True)),
                ('program_change_to', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_change_from', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_change_to', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_objective_change_from', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_objective_change_to', models.CharField(blank=True, max_length=100, null=True)),
                ('requirement_term_year', models.CharField(blank=True, max_length=4, null=True)),
                ('requirement_term_catalog', models.CharField(blank=True, max_length=100, null=True)),
                ('requirement_term_career', models.CharField(blank=True, max_length=100, null=True)),
                ('requirement_term_program_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_plan_degree_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_new_plan_primary_or_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('other_current_plans_or_minors', models.TextField(blank=True, null=True)),
                ('second_degree_type', models.CharField(blank=True, max_length=100, null=True)),
                ('minor_change_from', models.CharField(blank=True, max_length=100, null=True)),
                ('minor_change_to', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_minor', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_requirement_exception_details', models.TextField(blank=True, null=True)),
                ('special_problems_course_list', models.TextField(blank=True, null=True)),
                ('course_overload_gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('course_overload_credit_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('course_overload_course_list', models.TextField(blank=True, null=True)),
                ('graduate_leave_of_absence_request_details', models.TextField(blank=True, null=True)),
                ('graduate_reinstatement_request_details', models.TextField(blank=True, null=True)),
                ('other_request_details', models.TextField(blank=True, null=True)),
                ('explanation_of_request', models.TextField(blank=True, null=True)),
                ('student_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
