# Generated by Django 5.1.6 on 2025-04-13 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0010_generalpetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCLResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ps_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('initial_adjustment_issues', models.BooleanField(default=False)),
                ('initial_adjustment_explanation', models.TextField(blank=True, null=True)),
                ('improper_course_level_placement', models.BooleanField(default=False)),
                ('iclp_class1', models.CharField(blank=True, max_length=50, null=True)),
                ('iclp_professor1', models.CharField(blank=True, max_length=100, null=True)),
                ('iclp_professor_signature1', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('iclp_date1', models.DateTimeField(blank=True, null=True)),
                ('iclp_class2', models.CharField(blank=True, max_length=50, null=True)),
                ('iclp_professor2', models.CharField(blank=True, max_length=100, null=True)),
                ('iclp_professor_signature2', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('iclp_date2', models.DateTimeField(blank=True, null=True)),
                ('medical_reason', models.BooleanField(default=False)),
                ('medical_letter_attached', models.BooleanField(default=False)),
                ('final_semester', models.BooleanField(default=False)),
                ('final_semester_hours_needed', models.IntegerField(blank=True, null=True)),
                ('concurrent_enrollment', models.BooleanField(default=False)),
                ('concurrent_university_name', models.CharField(blank=True, max_length=100, null=True)),
                ('concurrent_hours_uh', models.IntegerField(blank=True, null=True)),
                ('concurrent_hours_other', models.IntegerField(blank=True, null=True)),
                ('semester_fall', models.BooleanField(default=False)),
                ('semester_spring', models.BooleanField(default=False)),
                ('year_last_digit', models.IntegerField(blank=True, null=True)),
                ('drop_courses', models.CharField(blank=True, max_length=255, null=True)),
                ('remaining_hours_uh', models.IntegerField(blank=True, null=True)),
                ('advisor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('advisor_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('advisor_date', models.DateTimeField(blank=True, null=True)),
                ('isss_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('isss_date', models.DateTimeField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to='delta.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcl_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RCLDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='rcl_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='delta.rclresponses')),
            ],
        ),
        migrations.CreateModel(
            name='TWResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ps_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_career', models.CharField(blank=True, max_length=100, null=True)),
                ('student_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('withdrawal_term_fall', models.BooleanField(default=False)),
                ('withdrawal_term_spring', models.BooleanField(default=False)),
                ('withdrawal_term_summer', models.BooleanField(default=False)),
                ('withdrawal_year', models.IntegerField(blank=True, null=True)),
                ('financial_aid_ack', models.BooleanField(default=False)),
                ('international_students_ack', models.BooleanField(default=False)),
                ('student_athlete_ack', models.BooleanField(default=False)),
                ('veterans_ack', models.BooleanField(default=False)),
                ('graduate_students_ack', models.BooleanField(default=False)),
                ('doctoral_students_ack', models.BooleanField(default=False)),
                ('housing_ack', models.BooleanField(default=False)),
                ('dining_ack', models.BooleanField(default=False)),
                ('parking_ack', models.BooleanField(default=False)),
                ('supporting_documents_attached', models.BooleanField(default=False)),
                ('supporting_document_path', models.FileField(blank=True, null=True, upload_to='tw_documents/')),
                ('is_finalized', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_responses', to='delta.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tw_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TWDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='tw_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='delta.twresponses')),
            ],
        ),
    ]
