# Generated by Django 5.1.6 on 2025-04-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0011_rclresponses_rcldocuments_twresponses_twdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcldocuments',
            name='response',
        ),
        migrations.RemoveField(
            model_name='rclresponses',
            name='request',
        ),
        migrations.RemoveField(
            model_name='rclresponses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twdocuments',
            name='response',
        ),
        migrations.RemoveField(
            model_name='twresponses',
            name='request',
        ),
        migrations.RemoveField(
            model_name='twresponses',
            name='user',
        ),
        migrations.AddField(
            model_name='rcldocuments',
            name='response_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rclresponses',
            name='request_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rclresponses',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twdocuments',
            name='response_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twresponses',
            name='request_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twresponses',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
