# Generated by Django 5.1.6 on 2025-04-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0012_remove_rcldocuments_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpetition',
            name='is_new_plan_primary_or_secondary',
        ),
        migrations.RemoveField(
            model_name='generalpetition',
            name='other_current_plans_or_minors',
        ),
        migrations.RemoveField(
            model_name='generalpetition',
            name='requirement_term_year',
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='Q9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='additional_plan_degree_type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='primary_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='secondary_plan',
            field=models.BooleanField(default=False),
        ),
    ]
