# Generated by Django 4.2.20 on 2025-04-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0013_delegation_unit_customuser_unit_request_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_org_approver',
            field=models.BooleanField(default=False),
        ),
    ]
