# Generated by Django 5.1.6 on 2025-04-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0013_remove_generalpetition_is_new_plan_primary_or_secondary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('change_major', 'Change Major'), ('change_address', 'Change Address'), ('general_petition', 'General Petition')], max_length=20),
        ),
    ]
