# Generated by Django 5.1.6 on 2025-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0014_alter_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpetition',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
