# Generated by Django 4.2.20 on 2025-04-18 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0015_generalpetition_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpetition',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
        migrations.AddField(
            model_name='generalpetition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='general_petitions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rclresponses',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
        migrations.AddField(
            model_name='twresponses',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
    ]
